# sonar-project.properties
sonar.projectKey=Jake220408141_7.1CDevSecOps.Part2
sonar.organization=jake220408141
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8

